Add example authorization capabilities for operations.
decentralized-identity/confidential-storage pull request #142
Opened 2020-12-08 01:55 UTC by dmitrizagidulin

2020-12-08 03:12 UTC, OR13 commented on index.html
> +    // ...
please provide a complete proof, we need to show that the invoker and the delegator are different identifiers.

2020-12-10 19:29 UTC, dmitrizagidulin commented on index.html
> +    // ...
Can we do that in a separate PR? (It might help to provide more explanation of key hierarchy for delegation, etc).

2020-12-10 20:55 UTC, dlongley commented on index.html
> +        in terms of allowed actions, or is 'write' sufficient?</p>
Current implementations only use `write`. Similarly, `write` is also used for `delete` since deleting requires tombstoning documents so that sequence numbers are preserved.

2020-12-10 20:56 UTC, dlongley commented on index.html
> +        in terms of allowed actions, or is 'write' sufficient?</p>
So, I'd recommend we keep it to `read` and `write` only until it's clear those are insufficient (favor simplicity).

2020-12-10 21:04 UTC, dlongley commented on index.html
> +        in terms of allowed actions, or is 'write' sufficient?</p>
Side note: 'create' is effectively implemented based on what the invocation target target is. Either you can 'write' to the collection of documents (i.e., you can 'create' documents) or you can 'write' to a specific document only.

2020-12-13 17:56 UTC, dlongley approved these changes
Approving with a few suggestions. I think this helps move things forward.

2020-12-13 17:56 UTC, dlongley commented on index.html
> +All operations perfomed by an Encrypted Data Vault must carry appropriate
```suggestion
All operations performed by an Encrypted Data Vault must carry appropriate
```

2020-12-13 17:56 UTC, dlongley commented on index.html
> +This operation creates an encrypted resource (Document or Stream), in a given
```suggestion
This operation creates an encrypted resource (a Document with or without an associated Stream), in a given
```

2020-12-13 17:56 UTC, dlongley commented on index.html
> +          <h4>Delete Resource (Document or Stream)</h4>
```suggestion
          <h4>Delete Resource (Document with or without an associated Stream)</h4>
```

2020-12-13 17:56 UTC, dlongley commented on index.html
> +behind for replication purposes).
At present the "delete" is performed by the client creating such a tombstone (an empty document) and sending it to the server. There's still more discussion to be had around preserving resource history (e.g., whether or not all EDVs MUST support it and how that would look and how we may forcibly remove that history to "fully" delete a resource making it non-recoverable). It may be that a separate history API would be involved there with different capabilities to read/write required.

2020-12-13 17:56 UTC, dlongley commented on index.html
> +  "invoker": "did:example:abcd#key1",
So, I'm not sure if we want all of these examples to use just a key vs. a plain DID -- or if we'd want to have separate examples with plain DIDs. Just making note that all of the examples here strongly bound the capability to a specific key vs. allowing key rotation.

2020-12-13 17:56 UTC, dlongley commented on index.html
> +Should there be a separate allowed action for querying on an index?
I would say that the expected root capability for querying would be the same as the one for the `/documents` endpoint; you must be able to read all documents to be permitted to perform a query.

2020-12-13 17:56 UTC, dlongley commented on index.html
> +  "invocationTarget": "https://example.com/edvs/z4sRgBJJLnYy/docs",
Note: The current implementations spell out `documents` in the HTTP API.

```suggestion
  "invocationTarget": "https://example.com/edvs/z4sRgBJJLnYy/documents",
```

2020-12-14 19:52 UTC, OR13 commented on index.html
> +  "invoker": "did:example:abcd#key1",
I would prefer to pick a position on this, and there be only 1, I would suggest we support key rotation, and not bind this to a specific key.

2020-12-14 19:52 UTC, OR13 commented on index.html
> +Should there be a separate allowed action for querying on an index?
can we add an example of this?

2020-12-14 19:54 UTC, OR13 commented on index.html
> +  "invoker": "did:example:abcd#key1",
I opened https://github.com/decentralized-identity/confidential-storage/issues/147 so we can merge this, but noting that its an open issue.

2020-12-14 19:55 UTC, OR13 commented on index.html
> +behind for replication purposes).
@dlongley can you convert this comment to an issue or propose changes?

2020-12-14 19:57 UTC, OR13 commented on index.html
> +    // ...
https://github.com/decentralized-identity/confidential-storage/issues/148 opened and assigned

2020-12-14 19:58 UTC, OR13 commented on index.html
> +Should there be a separate allowed action for querying on an index?
or convert to an issue.a

2020-12-14 20:53 UTC, dlongley commented on index.html
> +behind for replication purposes).
Filed #149.

2020-12-14 21:08 UTC, dlongley commented on index.html
> +Should there be a separate allowed action for querying on an index?
Opened #150.

2020-12-15 14:18 UTC, llorllale commented on index.html
> +        in terms of allowed actions, or is 'write' sufficient?</p>
Yes - the meaning of `write` depends on the context. Eg. writing to the `/encrypted-data-vaults` endpoint implies creation whereas writing to `/encrypted-data-vaults/{vaultID}/documents/{docID}` implies update. Both are different invocation targets.

2020-12-21 19:55 UTC, OR13 requested changes
Would like to see @dlongley 's comments merged / URLS updated.

2021-01-12 01:35 UTC, dmitrizagidulin commented on index.html
> +        in terms of allowed actions, or is 'write' sufficient?</p>
Issue removed; going with 'write' for the moment.

2021-09-16 19:57 UTC, dmitrizagidulin commented
Issues in comments addressed, PR moved to the new repo -- https://github.com/decentralized-identity/edv-spec/pull/75.

2021-09-16 19:57 UTC, closed without merging